name: Meta Regression Analysis

on:
  workflow_call:
    inputs:
      item_type_singular:
        description: "Singular name for the items being compared (e.g., test, file)."
        required: false
        type: string
        default: "item"
      item_type_plural:
        description: "Plural name for the items being compared (e.g., tests, files)."
        required: false
        type: string
        default: "items"
      pr_number:
        description: "Pull request number for artifact naming."
        required: false
        type: string
      run_id:
        description: "Current run ID for artifact naming if PR number is not available."
        required: true
        type: string
      target_branch_artifact_name:
        description: "Name of the artifact containing target branch data."
        required: true
        type: string
      pr_branch_artifact_name:
        description: "Name of the artifact containing PR branch data."
        required: true
        type: string
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
    outputs:
      has_regressions:
        description: "Boolean indicating if regressions were found."
        value: ${{ jobs.analyze.outputs.HAS_REGRESSIONS }}
      regression_count:
        description: "Number of regressions found."
        value: ${{ jobs.analyze.outputs.REGRESSION_COUNT }}
      regression_details_file_name:
        description: "Name of the artifact file containing regression details."
        value: "regression_details.txt"

jobs:
  analyze:
    runs-on: ${{ inputs.runs_on }}
    outputs:
      HAS_REGRESSIONS: ${{ steps.check-regressions-script.outputs.HAS_REGRESSIONS }}
      REGRESSION_COUNT: ${{ steps.check-regressions-script.outputs.REGRESSION_COUNT }}
    steps:
      - name: Download target branch data
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.target_branch_artifact_name }}
          path: ./target_data
        continue-on-error: true

      - name: Download PR branch data
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.pr_branch_artifact_name }}
          path: ./pr_data
        continue-on-error: true

      - name: Run regression analysis script
        id: check-regressions-script
        env:
          ITEM_TYPE_SINGULAR_ENV: "${{ inputs.item_type_singular }}"
          ITEM_TYPE_PLURAL_ENV: "${{ inputs.item_type_plural }}"
        run: |
          # Create debug file for detailed output
          exec 3>&1 4>&2
          exec 1> >(tee -a debug_regression_analysis.log) 2>&1

          echo "Running regression analysis..."

          python3 - <<'EOF'
          import json
          import os
          import sys
          import glob

          item_type_s = os.environ.get('ITEM_TYPE_SINGULAR_ENV', 'item')
          item_type_p = os.environ.get('ITEM_TYPE_PLURAL_ENV', 'items')

          regression_items_list = []
          has_regressions_output = "false"
          regression_count_output = 0

          try:
              def load_data_from_artifact_dir(artifact_dir, description):
                  """Load data from JSON files in artifact directory with properties structure."""
                  print(f"Looking for data files in {artifact_dir} for {description}")
                  
                  # Look for common test data file patterns
                  json_files = []
                  for pattern in ['*test_data.json', '*.json']:
                      json_files.extend(glob.glob(os.path.join(artifact_dir, pattern)))
                  
                  if not json_files:
                      print(f"No JSON files found in {artifact_dir} for {description}")
                      return {}
                  
                  # Use the first JSON file found (should be the main data file)
                  data_file = json_files[0]
                  print(f"Loading data from {data_file}")
                  
                  try:
                      with open(data_file, 'r') as f:
                          data = json.load(f)
                      print(f"Successfully loaded data from {data_file}, keys: {list(data.keys()) if isinstance(data, dict) else 'not a dict'}")
                      return data if isinstance(data, dict) else {}
                  except json.JSONDecodeError as e:
                      print(f"::warning::JSONDecodeError for {description}: {e}")
                      return {}
                  except Exception as e:
                      print(f"::warning::Error reading {description}: {e}")
                      return {}

              # Load data from artifact directories
              target_data = load_data_from_artifact_dir('./target_data', "Target branch data")
              pr_data = load_data_from_artifact_dir('./pr_data', "PR branch data")
              
              # Extract passing items from target data
              target_passing = []
              if isinstance(target_data, dict):
                  # Try different possible keys for passing items
                  for key in ['passing_tests', 'passing_items', 'passed_tests', 'passed_items']:
                      if key in target_data and isinstance(target_data[key], list):
                          target_passing = target_data[key]
                          print(f"Found {len(target_passing)} passing {item_type_p} using key '{key}' from target data")
                          break
                  
                  if not target_passing:
                      print(f"::warning::No passing {item_type_p} found in target data. Available keys: {list(target_data.keys())}")
              
              # Extract failing items from PR data  
              pr_failing = []
              if isinstance(pr_data, dict):
                  # Try different possible keys for failing items
                  for key in ['failing_tests', 'failing_items', 'failed_tests', 'failed_items']:
                      if key in pr_data and isinstance(pr_data[key], list):
                          pr_failing = pr_data[key]
                          print(f"Found {len(pr_failing)} failing {item_type_p} using key '{key}' from PR data")
                          break
                  
                  if not pr_failing:
                      print(f"::warning::No failing {item_type_p} found in PR data. Available keys: {list(pr_data.keys())}")
              
              print(f"Parsed {len(target_passing)} passing/clean {item_type_p} from target branch.")
              print(f"Parsed {len(pr_failing)} failing/issue {item_type_p} from PR branch.")
              
              target_passing_set = set(target_passing)
              pr_failing_set = set(pr_failing)
              
              regression_items_list = sorted(list(target_passing_set.intersection(pr_failing_set)))
              
              if regression_items_list:
                  print(f"Found {len(regression_items_list)} regression(s)!")
                  has_regressions_output = "true"
                  regression_count_output = len(regression_items_list)
                  with open("regression_details.txt", "w") as f:
                      f.write(f"Found {len(regression_items_list)} {item_type_p} that were passing/clean in the target branch but are now failing/have issues in the PR branch:\n\n")
                      for idx, item in enumerate(regression_items_list, 1):
                          f.write(f"{idx}. {item}\n")
                  print("Regression details written to regression_details.txt")
              else:
                  print(f"No new regressions found for {item_type_p}.")
                  with open("regression_details.txt", "w") as f:
                      f.write(f"No new regressions detected for {item_type_p} (items that were passing/clean in target and are now failing/with issues in PR).\n")

          except Exception as e:
              print(f"::error::Error in regression analysis script: {e}", file=sys.stderr)
              import traceback
              print(traceback.format_exc(), file=sys.stderr)
              with open("regression_details.txt", "w") as f:
                  f.write(f"An error occurred during regression analysis: {e}\n")

          github_output_file = os.environ.get('GITHUB_OUTPUT')
          if github_output_file:
              with open(github_output_file, 'a') as f_out:
                  f_out.write(f'HAS_REGRESSIONS={has_regressions_output}\n')
                  f_out.write(f'REGRESSION_COUNT={regression_count_output}\n')
              print(f"Output HAS_REGRESSIONS={has_regressions_output} to GITHUB_OUTPUT")
              print(f"Output REGRESSION_COUNT={regression_count_output} to GITHUB_OUTPUT")
          else:
              print("::warning::GITHUB_OUTPUT environment variable not set.")
          EOF

          # Restore stdout/stderr for GitHub Actions
          exec 1>&3 2>&4

          echo "Regression analysis script completed."

          # Only show regression summary in logs if regressions found
          if [ -f "regression_details.txt" ]; then
            REGRESSION_COUNT=$(grep -c "^[0-9]\+\." regression_details.txt || echo "0")
            if [ "$REGRESSION_COUNT" -gt 0 ]; then
              echo "::error::Found $REGRESSION_COUNT regression(s). Details available in artifact."
            else
              echo "No regressions detected."
            fi
          fi

      - name: Upload debug logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression_analysis_debug_logs_${{ inputs.pr_number || inputs.run_id }}
          path: debug_regression_analysis.log
          retention-days: 7
          if-no-files-found: ignore

      - name: Fail job if regressions are found
        if: steps.check-regressions-script.outputs.HAS_REGRESSIONS == 'true'
        run: |
          echo "Regressions detected. Failing the job as per configuration."
          REGRESSION_COUNT_VAL=${{ steps.check-regressions-script.outputs.REGRESSION_COUNT }}
          echo "### :x: Regressions Found!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # Newline
          echo "**$REGRESSION_COUNT_VAL regression(s) detected.** This job was intentionally failed." >> $GITHUB_STEP_SUMMARY
          echo "The 'Upload regression details artifact' step will still attempt to upload details." >> $GITHUB_STEP_SUMMARY
          exit 1

      - name: Upload regression details artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: regression_details_pr_${{ inputs.pr_number || inputs.run_id }}_${{ inputs.item_type_plural }}
          path: regression_details.txt
          retention-days: 7
