name: Reusable - Build and Push to GHCR

on:
  workflow_call:
    inputs:
      build_type:
        description: 'Type of build, influences tagging. Expected values: "dev", "main", "legacy", "release".'
        required: true
        type: string
      git_ref:
        description: "The full Git reference (e.g., refs/heads/main, refs/tags/v1.2.3). Used for version tagging on releases."
        required: true
        type: string
      add_sha_tag:
        description: "Whether to add a tag with the short commit SHA."
        required: false
        type: boolean
        default: true
      build_args:
        description: "Build arguments to pass to Docker build (e.g., MY_ARG=value)."
        required: false
        type: string
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
jobs:
  build-and-push-ghcr:
    name: Build and Push Docker Image to GHCR
    runs-on: ${{ inputs.runs_on }}
    permissions:
      contents: read # To checkout the repository
      packages: write # To push packages to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: "recursive"
          fetch-depth: 0 # Recommended for docker/metadata-action for full git history access

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # In reusable workflow, github.repository is the caller repo
          tags: |
            # Dev build tag
            type=raw,value=dev,enable=${{ inputs.build_type == 'dev' }}

            # Main branch build (staging tag)
            type=raw,value=stg,enable=${{ inputs.build_type == 'main' }}

            # Legacy build tag
            type=raw,value=legacy,enable=${{ inputs.build_type == 'legacy' }}

            # Release build tags
            type=raw,value=prod,enable=${{ inputs.build_type == 'release' }}
            type=raw,value=latest,enable=${{ inputs.build_type == 'release' }}
            # Version tag from git_ref (e.g., v1.0.0 from refs/tags/v1.0.0)
            # Ensure inputs.git_ref is a tag like refs/tags/v1.0.0 for this to work as expected.
            type=ref,event=tag,ref=${{ inputs.git_ref }},enable=${{ inputs.build_type == 'release' }}

            # SHA tag (short commit hash)
            type=sha,prefix=,enable=${{ inputs.add_sha_tag == true }}

      - name: Check for LANDING_ONLY build arg
        id: check_landing
        run: |
          echo "Original build_args:"
          echo "${{ inputs.build_args }}"

          if echo "${{ inputs.build_args }}" | grep -q "LANDING_ONLY"; then
            echo "has_landing_only=true" >> $GITHUB_OUTPUT
            
            # For normal build: remove any line containing LANDING_ONLY
            filtered_args=$(echo "${{ inputs.build_args }}" | grep -v "LANDING_ONLY" | grep -v "^[[:space:]]*$")
            echo "filtered_build_args<<EOF" >> $GITHUB_OUTPUT
            echo "$filtered_args" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            
            echo "Normal build args (LANDING_ONLY removed):"
            echo "$filtered_args"
            
            # Debug: Show the LANDING_ONLY line specifically
            echo "LANDING_ONLY line from original:"
            echo "${{ inputs.build_args }}" | grep "LANDING_ONLY"
            
            # For landing build: ensure LANDING_ONLY=true is present
            # First remove any LANDING_ONLY line, then add LANDING_ONLY=true
            landing_args=$(echo "${{ inputs.build_args }}" | grep -v "LANDING_ONLY")
            landing_args="${landing_args}"$'\n'"LANDING_ONLY=true"
            
            echo "landing_build_args<<EOF" >> $GITHUB_OUTPUT
            echo "$landing_args" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            
            echo "Landing build args (LANDING_ONLY=true):"
            echo "$landing_args"
          else
            echo "has_landing_only=false" >> $GITHUB_OUTPUT
            echo "filtered_build_args<<EOF" >> $GITHUB_OUTPUT
            echo "${{ inputs.build_args }}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "No LANDING_ONLY found, using original args"
          fi

      - name: Extract Docker metadata for landing build
        id: meta_landing
        if: steps.check_landing.outputs.has_landing_only == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=landing

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile # Assuming Dockerfile is at the root of the calling repo
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ steps.check_landing.outputs.filtered_build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image with LANDING_ONLY
        if: steps.check_landing.outputs.has_landing_only == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta_landing.outputs.tags }}
          labels: ${{ steps.meta_landing.outputs.labels }}
          build-args: ${{ steps.check_landing.outputs.landing_build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
